DROP TABLE IF EXISTS UserInfo;
DROP TABLE IF EXISTS UserPhoneNumber;
DROP TABLE IF EXISTS UserAddress;
DROP TABLE IF EXISTS PendingAdventurer;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Quest;